-- =====================================================
-- Operation Log Table for Online Table Operations
-- Author: Principal Oracle Database Application Engineer
-- Version: 1.0
-- =====================================================

-- Create operation log table
CREATE TABLE operation_log (
    operation_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name       VARCHAR2(128) NOT NULL,
    operation_type   VARCHAR2(50) NOT NULL,
    status           VARCHAR2(20) NOT NULL,
    operation_time   TIMESTAMP DEFAULT SYSTIMESTAMP,
    message          VARCHAR2(4000),
    rows_processed   NUMBER,
    duration_ms      NUMBER,
    error_code       NUMBER,
    error_message    VARCHAR2(4000)
);

-- Create indexes for performance
CREATE INDEX idx_operation_log_table ON operation_log(table_name);
CREATE INDEX idx_operation_log_time ON operation_log(operation_time);
CREATE INDEX idx_operation_log_status ON operation_log(status);

-- Create sequence for operation IDs
CREATE SEQUENCE operation_id_seq START WITH 1 INCREMENT BY 1;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON operation_log TO PUBLIC;
GRANT SELECT ON operation_id_seq TO PUBLIC;
