-- =====================================================
-- Oracle Generic Strategy Configuration Table
-- Configuration table for maintenance strategy management
-- Author: Principal Oracle Database Application Engineer
-- Version: 1.0
-- =====================================================

-- Create generic strategy configuration table
CREATE TABLE generic_strategy_config (
    config_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name     VARCHAR2(50) NOT NULL,
    target_object     VARCHAR2(128) NOT NULL,
    target_type       VARCHAR2(30) NOT NULL,
    strategy_type     VARCHAR2(20) NOT NULL,
    -- Strategy-specific configuration (flexible JSON/CLOB)
    strategy_config   CLOB, -- JSON configuration
    -- Execution parameters
    execution_mode    VARCHAR2(20) DEFAULT 'AUTOMATIC', -- AUTOMATIC, MANUAL, SCHEDULED
    parallel_degree   NUMBER DEFAULT 1,
    batch_size        NUMBER DEFAULT 1000,
    timeout_seconds  NUMBER DEFAULT 3600,
    -- Resource management
    resource_limits   VARCHAR2(1000),
    priority_level    NUMBER DEFAULT 5, -- 1-10, 10 being highest
    -- Scheduling
    schedule_expression VARCHAR2(200), -- Cron-like expression
    schedule_timezone VARCHAR2(50) DEFAULT 'UTC',
    -- Dependencies and prerequisites
    depends_on_strategies VARCHAR2(1000), -- Comma-separated strategy names
    prerequisite_checks VARCHAR2(4000),
    -- Lifecycle management
    created_date      DATE DEFAULT SYSDATE,
    created_by        VARCHAR2(30) DEFAULT USER,
    last_modified     DATE DEFAULT SYSDATE,
    last_modified_by  VARCHAR2(30) DEFAULT USER,
    is_active         CHAR(1) DEFAULT 'Y',
    -- Enhanced fields for strategy management
    version           VARCHAR2(20) DEFAULT '1.0',
    description       VARCHAR2(1000),
    tags              VARCHAR2(1000), -- Comma-separated tags
    -- Performance tracking
    execution_count   NUMBER DEFAULT 0,
    success_count     NUMBER DEFAULT 0,
    failure_count     NUMBER DEFAULT 0,
    avg_duration_ms   NUMBER,
    last_execution    DATE,
    last_success      DATE,
    last_failure      DATE,
    -- Migration and deployment
    deployment_status VARCHAR2(20) DEFAULT 'PENDING',
    deployment_started DATE,
    deployment_completed DATE,
    rollback_available CHAR(1) DEFAULT 'N',
    -- Monitoring and alerting
    monitoring_enabled CHAR(1) DEFAULT 'Y',
    alert_thresholds  VARCHAR2(1000), -- JSON thresholds
    notification_config VARCHAR2(1000), -- JSON notification config
    -- Foreign key constraints
    CONSTRAINT fk_generic_strategy_name FOREIGN KEY (strategy_name) 
        REFERENCES generic_strategy_types(strategy_name),
    CONSTRAINT fk_generic_strategy_type FOREIGN KEY (strategy_type) 
        REFERENCES generic_strategy_types(strategy_type),
    CONSTRAINT fk_generic_target_type_config FOREIGN KEY (target_type) 
        REFERENCES generic_target_types(target_type),
    CONSTRAINT fk_generic_strategy_active FOREIGN KEY (is_active) 
        REFERENCES generic_yes_no(value),
    CONSTRAINT fk_generic_deployment_status FOREIGN KEY (deployment_status) 
        REFERENCES generic_deployment_status(status),
    CONSTRAINT fk_generic_rollback_available FOREIGN KEY (rollback_available) 
        REFERENCES generic_yes_no(value),
    CONSTRAINT fk_generic_monitoring_enabled FOREIGN KEY (monitoring_enabled) 
        REFERENCES generic_yes_no(value)
);

-- Create indexes
CREATE UNIQUE INDEX idx_generic_strategy_target ON generic_strategy_config(strategy_name, target_object, is_active);
CREATE INDEX idx_generic_strategy_name ON generic_strategy_config(strategy_name);
CREATE INDEX idx_generic_strategy_type ON generic_strategy_config(strategy_type);
CREATE INDEX idx_generic_strategy_active ON generic_strategy_config(is_active);
CREATE INDEX idx_generic_strategy_modified ON generic_strategy_config(last_modified);
CREATE INDEX idx_generic_strategy_target_type ON generic_strategy_config(target_type);

-- Enhanced indexes for strategy management
CREATE INDEX idx_generic_strategy_deployment ON generic_strategy_config(deployment_status);
CREATE INDEX idx_generic_strategy_priority ON generic_strategy_config(priority_level);
CREATE INDEX idx_generic_strategy_execution ON generic_strategy_config(last_execution);
CREATE INDEX idx_generic_strategy_tags ON generic_strategy_config(tags);

PROMPT Generic strategy configuration table created successfully
