-- =====================================================
-- Oracle Partition Maintenance Jobs Table
-- Configuration table for automated partition maintenance
-- Author: Principal Oracle Database Application Engineer
-- Version: 1.0
-- =====================================================

-- Create maintenance job configuration table
CREATE TABLE partition_maintenance_jobs (
    job_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name        VARCHAR2(128) NOT NULL,
    job_type          VARCHAR2(50) NOT NULL,
    schedule_type     VARCHAR2(20) NOT NULL,
    schedule_value    VARCHAR2(100),
    is_active         CHAR(1) DEFAULT 'Y',
    last_run          DATE,
    next_run          DATE,
    created_date      DATE DEFAULT SYSDATE,
    created_by        VARCHAR2(30) DEFAULT USER,
    -- Enhanced fields for optimized maintenance
    last_modified     DATE DEFAULT SYSDATE,
    last_modified_by  VARCHAR2(30) DEFAULT USER,
    execution_count   NUMBER DEFAULT 0,
    avg_duration_ms   NUMBER,
    last_duration_ms  NUMBER,
    last_status       VARCHAR2(20),
    error_count       NUMBER DEFAULT 0,
    last_error        VARCHAR2(4000),
    -- Foreign key constraints
    CONSTRAINT fk_job_type FOREIGN KEY (job_type) 
        REFERENCES partition_job_types(job_type),
    CONSTRAINT fk_schedule_type FOREIGN KEY (schedule_type) 
        REFERENCES partition_schedule_types(schedule_type),
    CONSTRAINT fk_job_active FOREIGN KEY (is_active) 
        REFERENCES partition_yes_no(value),
    CONSTRAINT fk_job_last_status FOREIGN KEY (last_status) 
        REFERENCES partition_operation_status(status)
);

-- Create indexes for performance
CREATE INDEX idx_maint_jobs_table ON partition_maintenance_jobs(table_name);
CREATE INDEX idx_maint_jobs_type ON partition_maintenance_jobs(job_type);
CREATE INDEX idx_maint_jobs_schedule ON partition_maintenance_jobs(schedule_type);
CREATE INDEX idx_maint_jobs_active ON partition_maintenance_jobs(is_active);
CREATE INDEX idx_maint_jobs_next_run ON partition_maintenance_jobs(next_run);

-- Enhanced indexes for optimized maintenance
CREATE INDEX idx_maint_jobs_last_status ON partition_maintenance_jobs(last_status);
CREATE INDEX idx_maint_jobs_error_count ON partition_maintenance_jobs(error_count);
CREATE INDEX idx_maint_jobs_execution_count ON partition_maintenance_jobs(execution_count);
CREATE INDEX idx_maint_jobs_last_modified ON partition_maintenance_jobs(last_modified);

-- Create interval partitioned table for automatic partition creation
ALTER TABLE partition_maintenance_jobs 
PARTITION BY RANGE (created_date) 
INTERVAL (NUMTODSINTERVAL(1, 'YEAR')) (
    PARTITION p_jobs_initial VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD'))
);

PROMPT Partition maintenance jobs table created successfully
