-- =====================================================
-- Oracle Partition Strategy Configuration Table
-- Configuration table for partition strategy management
-- Author: Principal Oracle Database Application Engineer
-- Version: 1.0
-- =====================================================

-- Create partition strategy configuration table
CREATE TABLE partition_strategy_config (
    config_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name        VARCHAR2(128) NOT NULL,
    strategy_type     VARCHAR2(20) NOT NULL,
    partition_column  VARCHAR2(128),
    interval_value    VARCHAR2(50),
    tablespace_prefix VARCHAR2(30),
    retention_days    NUMBER DEFAULT 90,
    auto_maintenance  CHAR(1) DEFAULT 'Y',
    created_date      DATE DEFAULT SYSDATE,
    created_by        VARCHAR2(30) DEFAULT USER,
    last_modified     DATE DEFAULT SYSDATE,
    last_modified_by  VARCHAR2(30) DEFAULT USER,
    is_active         CHAR(1) DEFAULT 'Y',
    -- Enhanced fields for optimized strategy management
    subpartition_type VARCHAR2(20),
    subpartition_column VARCHAR2(128),
    partition_count   NUMBER,
    subpartition_count NUMBER,
    compression_type  VARCHAR2(20) DEFAULT 'NONE',
    parallel_degree   NUMBER DEFAULT 1,
    online_operations CHAR(1) DEFAULT 'Y',
    migration_status  VARCHAR2(20) DEFAULT 'PENDING',
    migration_started DATE,
    migration_completed DATE,
    migration_duration_ms NUMBER,
    rollback_available CHAR(1) DEFAULT 'N',
    performance_score NUMBER,
    last_analyzed     DATE,
    -- Foreign key constraints
    CONSTRAINT fk_strategy_type FOREIGN KEY (strategy_type) 
        REFERENCES partition_strategy_types(strategy_type),
    CONSTRAINT fk_subpartition_type FOREIGN KEY (subpartition_type) 
        REFERENCES partition_strategy_types(strategy_type),
    CONSTRAINT fk_auto_maintenance FOREIGN KEY (auto_maintenance) 
        REFERENCES partition_yes_no(value),
    CONSTRAINT fk_strategy_active FOREIGN KEY (is_active) 
        REFERENCES partition_yes_no(value),
    CONSTRAINT fk_online_operations FOREIGN KEY (online_operations) 
        REFERENCES partition_yes_no(value),
    CONSTRAINT fk_rollback_available FOREIGN KEY (rollback_available) 
        REFERENCES partition_yes_no(value),
    CONSTRAINT fk_migration_status FOREIGN KEY (migration_status) 
        REFERENCES partition_migration_status(status),
    CONSTRAINT fk_compression_type FOREIGN KEY (compression_type) 
        REFERENCES partition_compression_types(compression_type)
);

-- Create indexes
CREATE UNIQUE INDEX idx_part_strategy_table ON partition_strategy_config(table_name, is_active);
CREATE INDEX idx_part_strategy_type ON partition_strategy_config(strategy_type);
CREATE INDEX idx_part_strategy_active ON partition_strategy_config(is_active);
CREATE INDEX idx_part_strategy_modified ON partition_strategy_config(last_modified);

-- Enhanced indexes for optimized strategy management
CREATE INDEX idx_part_strategy_migration_status ON partition_strategy_config(migration_status);
CREATE INDEX idx_part_strategy_online_ops ON partition_strategy_config(online_operations);
CREATE INDEX idx_part_strategy_performance ON partition_strategy_config(performance_score);
CREATE INDEX idx_part_strategy_subpartition ON partition_strategy_config(subpartition_type);
CREATE INDEX idx_part_strategy_compression ON partition_strategy_config(compression_type);

PROMPT Partition strategy configuration table created successfully
