aCREATE TABLE CIM_OFM_SMG3_LOGGING_SIMPLE (
    TRACE_ID VARCHAR2(36 BYTE),
    ALIAS VARCHAR2(8 BYTE),
    AUDIT_CREATE_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    SMG3_LOGGING_DATA CLOB,
    FILTRATION_JSON_DATA CLOB
)
PARTITION BY RANGE (AUDIT_CREATE_DATE)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION p_before_2025 VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
)
LOB (FILTRATION_JSON_DATA) STORE AS SECUREFILE (TABLESPACE MAV_LOB),
LOB (SMG3_LOGGING_DATA) STORE AS SECUREFILE (TABLESPACE MAV_HIST_LOB)
TABLESPACE DBRT_DATA;
