CREATE TABLE CIM_OFM_SMG3_LOGGING (
    TRACE_ID VARCHAR2(36 BYTE),
    ALIAS VARCHAR2(8 BYTE),
    AUDIT_CREATE_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    SMG3_LOGGING_DATA CLOB,
    FILTRATION_JSON_DATA CLOB
)
-- Partition the main table data
PARTITION BY RANGE (AUDIT_CREATE_DATE)
INTERVAL (NUMTODSINTERVAL(1, 'DAY')) -- Create new partition every day
SUBPARTITION BY HASH (TRACE_ID) SUBPARTITIONS 2 -- Create 8 hash subpartitions per interval partition
(
    -- Define the initial range partition (the "transition point")
    PARTITION p_before_2025 VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
)
-- Use a subpartition template for LOB storage
SUBPARTITION TEMPLATE (
    SUBPARTITION s1 TABLESPACE MAV_LOB,
    SUBPARTITION s2 TABLESPACE MAV_HIST_LOB
)
-- Define the LOB storage for the LOB columns
LOB (FILTRATION_JSON_DATA) STORE AS SECUREFILE (TABLESPACE MAV_LOB),
LOB (SMG3_LOGGING_DATA) STORE AS SECUREFILE (TABLESPACE MAV_HIST_LOB)
TABLESPACE DBRT_DATA;