-- =====================================================
-- Modern Oracle Logging Infrastructure
-- Single table + views approach with JSON support
-- Author: Principal Oracle Database Application Engineer
-- Version: 3.0 (Modern)
-- =====================================================

-- Main logging table with JSON support and partitioning
CREATE TABLE partition_operations_log (
    log_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    log_timestamp     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    session_id        VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID'),
    operation_id      NUMBER,
    log_level         VARCHAR2(10) DEFAULT 'INFO', -- DEBUG, INFO, WARN, ERROR, FATAL
    log_type          VARCHAR2(20) DEFAULT 'OPERATION', -- OPERATION, PERFORMANCE, ERROR, AUDIT
    table_name        VARCHAR2(128),
    partition_name    VARCHAR2(128),
    operation_type    VARCHAR2(50),
    operation_status  VARCHAR2(20), -- STARTED, RUNNING, SUCCESS, FAILED, CANCELLED
    message           VARCHAR2(4000),
    error_code        NUMBER,
    error_message     VARCHAR2(4000),
    duration_ms       NUMBER,
    rows_processed    NUMBER,
    -- JSON column for flexible attributes (Oracle 19c+)
    attributes        JSON,
    -- Metadata
    username          VARCHAR2(128) DEFAULT USER,
    client_info       VARCHAR2(64) DEFAULT SYS_CONTEXT('USERENV', 'CLIENT_INFO'),
    module_name       VARCHAR2(48) DEFAULT SYS_CONTEXT('USERENV', 'MODULE'),
    action_name       VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'ACTION'),
    -- Partitioning column
    log_date          DATE GENERATED ALWAYS AS (CAST(log_timestamp AS DATE)),
    -- Constraints
    CONSTRAINT pk_partition_log PRIMARY KEY (log_id, log_date),
    CONSTRAINT chk_log_level CHECK (log_level IN ('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL')),
    CONSTRAINT chk_log_type CHECK (log_type IN ('OPERATION', 'PERFORMANCE', 'ERROR', 'AUDIT')),
    CONSTRAINT chk_operation_status CHECK (operation_status IN ('STARTED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED')),
    -- JSON constraint (Oracle 19c+)
    CONSTRAINT chk_attributes_json CHECK (attributes IS JSON)
) 
PARTITION BY RANGE (log_date) 
INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION p_initial VALUES LESS THAN (DATE '2025-01-01')
)
COMPRESS FOR OLTP;

-- Indexes for performance
CREATE INDEX idx_partition_log_timestamp ON partition_operations_log (log_timestamp) LOCAL;
CREATE INDEX idx_partition_log_operation ON partition_operations_log (operation_id, log_timestamp) LOCAL;
CREATE INDEX idx_partition_log_table ON partition_operations_log (table_name, log_timestamp) LOCAL;
CREATE INDEX idx_partition_log_status ON partition_operations_log (operation_status, log_level) LOCAL;
CREATE INDEX idx_partition_log_type ON partition_operations_log (log_type, log_timestamp) LOCAL;

-- JSON functional index for common attribute queries (Oracle 19c+)
CREATE INDEX idx_partition_log_json_parallel ON partition_operations_log (JSON_VALUE(attributes, '$.parallel_degree')) LOCAL;

-- Comments for documentation
COMMENT ON TABLE partition_operations_log IS 'Centralized logging for partition operations with JSON support';
COMMENT ON COLUMN partition_operations_log.attributes IS 'JSON column for flexible operation-specific attributes';
COMMENT ON COLUMN partition_operations_log.log_level IS 'Standard logging levels: DEBUG, INFO, WARN, ERROR, FATAL';
COMMENT ON COLUMN partition_operations_log.log_type IS 'Log categorization: OPERATION, PERFORMANCE, ERROR, AUDIT';

-- Sequence for operation IDs
CREATE SEQUENCE partition_operation_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE;

-- Grant permissions
GRANT SELECT ON partition_operations_log TO PUBLIC;
GRANT SELECT ON partition_operation_seq TO PUBLIC;