-- =====================================================
-- EXAMPLES: How to Add Subpartitioning to Existing Tables
-- Using your table_ops_pkg functions - EXAMPLES ONLY
-- =====================================================

SET SERVEROUTPUT ON SIZE 1000000

PROMPT ========================================
PROMPT EXAMPLES: Adding Subpartitioning to Existing Table
PROMPT From: INTERVAL partitioned by date
PROMPT To: INTERVAL-HASH subpartitioned by date + TRACE_ID
PROMPT ========================================

-- =====================================================
-- EXAMPLE 1: Basic Subpartitioning DDL Generation
-- =====================================================

DECLARE
    v_ddl CLOB;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== EXAMPLE: GENERATING SUBPARTITIONING DDL ===');
    
    -- Use the function from table_ops_pkg (implementation is in the package)
    v_ddl := table_ops_pkg.generate_add_subpartitioning_ddl(
        p_table_name            => 'CIM_OFM_SMG3_LOGGING_SIMPLE',
        p_subpartition_column   => 'TRACE_ID',
        p_subpartition_type     => 'HASH',
        p_tablespace_list       => 'MAV_LOB,MAV_HIST_LOB',
        p_subpartition_count    => 2,
        p_parallel_degree       => 4
    );
    
    DBMS_OUTPUT.PUT_LINE('Generated DDL from package function:');
    DBMS_OUTPUT.PUT_LINE('====================================');
    DBMS_OUTPUT.PUT_LINE(SUBSTR(v_ddl, 1, 2000)); -- Show first 2000 chars
    DBMS_OUTPUT.PUT_LINE('... (full DDL generated by package)');
    DBMS_OUTPUT.PUT_LINE('====================================');
    
END;
/

-- =====================================================
-- EXAMPLE 2: Online Redefinition Approach
-- =====================================================

DECLARE
    v_online_ddl CLOB;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== EXAMPLE: ONLINE REDEFINITION SCRIPT ===');
    
    -- Use the online redefinition function from table_ops_pkg
    v_online_ddl := table_ops_pkg.generate_online_subpartitioning_ddl(
        p_table_name            => 'CIM_OFM_SMG3_LOGGING_SIMPLE',
        p_subpartition_column   => 'TRACE_ID',
        p_subpartition_type     => 'HASH',
        p_tablespace_list       => 'MAV_LOB,MAV_HIST_LOB',
        p_subpartition_count    => 2,
        p_parallel_degree       => 4
    );
    
    DBMS_OUTPUT.PUT_LINE('Generated Online Redefinition Script:');
    DBMS_OUTPUT.PUT_LINE('====================================');
    DBMS_OUTPUT.PUT_LINE(SUBSTR(v_online_ddl, 1, 2000)); -- Show first 2000 chars
    DBMS_OUTPUT.PUT_LINE('... (full script generated by package)');
    DBMS_OUTPUT.PUT_LINE('====================================');
    
END;
/

-- =====================================================
-- EXAMPLE 3: Different Tablespace Configurations
-- =====================================================

DECLARE
    v_ddl CLOB;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== EXAMPLE: MULTIPLE TABLESPACE ROUND-ROBIN ===');
    
    -- Example with 3 tablespaces and 4 subpartitions
    v_ddl := table_ops_pkg.generate_add_subpartitioning_ddl(
        p_table_name            => 'CIM_OFM_SMG3_LOGGING_SIMPLE',
        p_subpartition_column   => 'TRACE_ID',
        p_subpartition_type     => 'HASH',
        p_tablespace_list       => 'MAV_LOB,MAV_HIST_LOB,DBRT_DATA',
        p_subpartition_count    => 4, -- Round-robin: TS1,TS2,TS3,TS1
        p_parallel_degree       => 8
    );
    
    DBMS_OUTPUT.PUT_LINE('Round-robin across 3 tablespaces with 4 subpartitions:');
    DBMS_OUTPUT.PUT_LINE('Generated by package function - ready to execute');
    
END;
/

PROMPT
PROMPT ========================================
PROMPT SUMMARY: Package Functions Available
PROMPT ========================================
PROMPT
PROMPT ✅ table_ops_pkg.generate_add_subpartitioning_ddl()
PROMPT   → Generates DDL to add subpartitioning to existing table
PROMPT   → Handles round-robin tablespace distribution
PROMPT   → Preserves existing structure and LOB storage
PROMPT
PROMPT ✅ table_ops_pkg.generate_online_subpartitioning_ddl()
PROMPT   → Generates DBMS_REDEFINITION script for online conversion
PROMPT   → Minimal downtime approach
PROMPT   → Includes error handling and rollback
PROMPT
PROMPT ✅ table_ddl_pkg.generate_partitioned_table_ddl()
PROMPT   → For creating new subpartitioned tables from scratch
PROMPT   → Full control over table structure
PROMPT
PROMPT 🎯 IMPLEMENTATION NOTE:
PROMPT   All actual code is in the package bodies
PROMPT   These examples show HOW TO USE the packages
PROMPT
PROMPT ========================================
    
    PROMPT ========================================

-- =====================================================
-- METHOD 2: Enhanced Function for Subpartitioning
-- =====================================================

PROMPT
PROMPT Method 2: Custom Function for Adding Subpartitioning
PROMPT

CREATE OR REPLACE FUNCTION generate_add_subpartitioning_ddl(
    p_table_name            IN VARCHAR2,
    p_subpartition_column   IN VARCHAR2,
    p_subpartition_type     IN VARCHAR2 DEFAULT 'HASH',
    p_tablespace_list       IN VARCHAR2, -- Comma-separated: 'TS1,TS2,TS3'
    p_subpartition_count    IN NUMBER DEFAULT NULL -- If NULL, uses tablespace count
) RETURN CLOB
IS
    v_ddl CLOB;
    v_new_table_name VARCHAR2(128);
    v_tablespaces sys.odcivarchar2list;
    v_subpart_count NUMBER;
    v_subpart_template CLOB := '';
    v_table_ddl CLOB;
    v_column_list CLOB;
    
    -- Cursor to get existing table structure
    CURSOR c_columns IS
        SELECT column_name, data_type, data_length, data_precision, data_scale, 
               nullable, data_default, column_id
        FROM user_tab_columns 
        WHERE table_name = UPPER(p_table_name)
        ORDER BY column_id;
        
    -- Cursor to get existing partition info
    CURSOR c_partitions IS
        SELECT partition_name, high_value, tablespace_name
        FROM user_tab_partitions 
        WHERE table_name = UPPER(p_table_name)
        ORDER BY partition_position;
        
    -- Cursor to get LOB storage info
    CURSOR c_lobs IS
        SELECT column_name, tablespace_name, securefile
        FROM user_lobs 
        WHERE table_name = UPPER(p_table_name);
        
BEGIN
    v_new_table_name := p_table_name || '_SUBPART';
    
    -- Parse tablespace list
    SELECT TRIM(REGEXP_SUBSTR(p_tablespace_list, '[^,]+', 1, level))
    BULK COLLECT INTO v_tablespaces
    FROM dual
    CONNECT BY REGEXP_SUBSTR(p_tablespace_list, '[^,]+', 1, level) IS NOT NULL;
    
    v_subpart_count := NVL(p_subpartition_count, v_tablespaces.COUNT);
    
    -- Build subpartition template
    v_subpart_template := 'SUBPARTITION TEMPLATE (' || CHR(10);
    FOR i IN 1..v_subpart_count LOOP
        v_subpart_template := v_subpart_template || 
            '    SUBPARTITION sp' || i || ' TABLESPACE ' || 
            v_tablespaces(MOD(i-1, v_tablespaces.COUNT) + 1);
        IF i < v_subpart_count THEN
            v_subpart_template := v_subpart_template || ',';
        END IF;
        v_subpart_template := v_subpart_template || CHR(10);
    END LOOP;
    v_subpart_template := v_subpart_template || ')';
    
    -- Build column definitions
    v_column_list := '';
    FOR rec IN c_columns LOOP
        v_column_list := v_column_list || '    ' || rec.column_name || ' ' || rec.data_type;
        
        -- Add precision/scale for numbers, length for strings
        IF rec.data_type = 'NUMBER' AND rec.data_precision IS NOT NULL THEN
            v_column_list := v_column_list || '(' || rec.data_precision;
            IF rec.data_scale IS NOT NULL AND rec.data_scale > 0 THEN
                v_column_list := v_column_list || ',' || rec.data_scale;
            END IF;
            v_column_list := v_column_list || ')';
        ELSIF rec.data_type LIKE 'VARCHAR2%' OR rec.data_type LIKE 'CHAR%' THEN
            v_column_list := v_column_list || '(' || rec.data_length || ' BYTE)';
        ELSIF rec.data_type LIKE 'TIMESTAMP%' THEN
            v_column_list := v_column_list || '(6)';
        END IF;
        
        -- Add default value
        IF rec.data_default IS NOT NULL THEN
            v_column_list := v_column_list || ' DEFAULT ' || TRIM(rec.data_default);
        END IF;
        
        v_column_list := v_column_list || ',' || CHR(10);
    END LOOP;
    
    -- Remove trailing comma
    v_column_list := RTRIM(v_column_list, ',' || CHR(10));
    
    -- Build main DDL
    v_ddl := '-- Add Subpartitioning to Existing Partitioned Table' || CHR(10);
    v_ddl := v_ddl || '-- Original: ' || p_table_name || CHR(10);
    v_ddl := v_ddl || '-- New: ' || v_new_table_name || CHR(10) || CHR(10);
    
    v_ddl := v_ddl || 'CREATE TABLE ' || v_new_table_name || ' (' || CHR(10);
    v_ddl := v_ddl || v_column_list || CHR(10);
    v_ddl := v_ddl || ')' || CHR(10);
    v_ddl := v_ddl || 'PARTITION BY RANGE (AUDIT_CREATE_DATE)' || CHR(10);
    v_ddl := v_ddl || 'INTERVAL (NUMTODSINTERVAL(1, ''DAY''))' || CHR(10);
    v_ddl := v_ddl || 'SUBPARTITION BY ' || UPPER(p_subpartition_type) || ' (' || UPPER(p_subpartition_column) || ')' || CHR(10);
    v_ddl := v_ddl || v_subpart_template || CHR(10);
    
    -- Add existing partitions
    v_ddl := v_ddl || '(' || CHR(10);
    FOR rec IN c_partitions LOOP
        v_ddl := v_ddl || '    PARTITION ' || rec.partition_name || 
                 ' VALUES LESS THAN (' || rec.high_value || ')';
        IF c_partitions%ROWCOUNT < (SELECT COUNT(*) FROM user_tab_partitions WHERE table_name = UPPER(p_table_name)) THEN
            v_ddl := v_ddl || ',';
        END IF;
        v_ddl := v_ddl || CHR(10);
    END LOOP;
    v_ddl := v_ddl || ')' || CHR(10);
    
    -- Add LOB storage
    FOR rec IN c_lobs LOOP
        v_ddl := v_ddl || 'LOB (' || rec.column_name || ') STORE AS ';
        IF rec.securefile = 'YES' THEN
            v_ddl := v_ddl || 'SECUREFILE ';
        END IF;
        v_ddl := v_ddl || '(TABLESPACE ' || rec.tablespace_name || ')' || CHR(10);
    END LOOP;
    
    -- Add main tablespace
    SELECT tablespace_name INTO v_table_ddl 
    FROM user_tables 
    WHERE table_name = UPPER(p_table_name);
    
    v_ddl := v_ddl || 'TABLESPACE ' || v_table_ddl || ';' || CHR(10) || CHR(10);
    
    -- Add data copy statement
    v_ddl := v_ddl || '-- Copy data from original table' || CHR(10);
    v_ddl := v_ddl || 'INSERT /*+ PARALLEL(8) APPEND */ INTO ' || v_new_table_name || CHR(10);
    v_ddl := v_ddl || 'SELECT * FROM ' || p_table_name || ';' || CHR(10) || CHR(10);
    v_ddl := v_ddl || 'COMMIT;' || CHR(10);
    
    RETURN v_ddl;
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'Error generating subpartitioning DDL: ' || SQLERRM;
END generate_add_subpartitioning_ddl;
/

-- =====================================================
-- METHOD 3: Use the Enhanced Function
-- =====================================================

PROMPT
PROMPT Method 3: Using Enhanced Function for Subpartitioning
PROMPT

DECLARE
    v_ddl CLOB;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== USING ENHANCED FUNCTION FOR SUBPARTITIONING ===');
    
    -- Generate DDL to add subpartitioning to existing table
    v_ddl := generate_add_subpartitioning_ddl(
        p_table_name            => 'CIM_OFM_SMG3_LOGGING_SIMPLE',
        p_subpartition_column   => 'TRACE_ID',
        p_subpartition_type     => 'HASH',
        p_tablespace_list       => 'MAV_LOB,MAV_HIST_LOB,DBRT_DATA', -- Round-robin these
        p_subpartition_count    => 4  -- 4 subpartitions for better distribution
    );
    
    DBMS_OUTPUT.PUT_LINE('Generated Subpartitioning DDL:');
    DBMS_OUTPUT.PUT_LINE('===================================');
    DBMS_OUTPUT.PUT_LINE(v_ddl);
    DBMS_OUTPUT.PUT_LINE('===================================');
    
END;
/

-- =====================================================
-- WHAT THE ENHANCED APPROACH PROVIDES
-- =====================================================

PROMPT
PROMPT ========================================
PROMPT ENHANCED SUBPARTITIONING CAPABILITIES
PROMPT ========================================
PROMPT
PROMPT ✅ Preserves existing INTERVAL partitioning by date
PROMPT ✅ Adds HASH subpartitioning on TRACE_ID
PROMPT ✅ Round-robin distribution across specified tablespaces
PROMPT ✅ Configurable number of subpartitions
PROMPT ✅ Preserves all LOB storage specifications
PROMPT ✅ Maintains column definitions and defaults
PROMPT ✅ Generates complete migration script
PROMPT
PROMPT TABLESPACE DISTRIBUTION EXAMPLE:
PROMPT   Subpartition 1 → MAV_LOB
PROMPT   Subpartition 2 → MAV_HIST_LOB  
PROMPT   Subpartition 3 → DBRT_DATA
PROMPT   Subpartition 4 → MAV_LOB (round-robin)
PROMPT
PROMPT PERFORMANCE BENEFITS:
PROMPT ✅ Partition pruning by date (existing)
PROMPT ✅ Subpartition pruning by TRACE_ID (new)
PROMPT ✅ Better parallel query execution
PROMPT ✅ Improved load balancing across storage
PROMPT ✅ Granular maintenance operations
PROMPT
PROMPT ========================================