-- =====================================================
-- EXAMPLES: Online Redefinition for Subpartitioning
-- Using table_ops_pkg functions - EXAMPLES ONLY
-- =====================================================

SET SERVEROUTPUT ON SIZE 1000000

PROMPT ========================================
PROMPT EXAMPLES: ONLINE SUBPARTITIONING WITH DBMS_REDEFINITION
PROMPT Zero-downtime conversion using your packages
PROMPT ========================================

-- =====================================================
-- EXAMPLE: Using Your Package for Online Redefinition
-- =====================================================

PROMPT
PROMPT Example: Generate Online Redefinition Script
PROMPT Benefits: Minimal downtime, online operation, automatic data sync
PROMPT

DECLARE
    v_online_ddl CLOB;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== ONLINE SUBPARTITIONING WITH DBMS_REDEFINITION ===');
    
    -- Use the function from table_ops_pkg (implementation is in the package)
    v_online_ddl := table_ops_pkg.generate_online_subpartitioning_ddl(
        p_table_name            => 'CIM_OFM_SMG3_LOGGING_SIMPLE',
        p_subpartition_column   => 'TRACE_ID',
        p_subpartition_type     => 'HASH',
        p_tablespace_list       => 'MAV_LOB,MAV_HIST_LOB',
        p_subpartition_count    => 2,
        p_parallel_degree       => 4
    );
    
    DBMS_OUTPUT.PUT_LINE('Generated Online Redefinition Script:');
    DBMS_OUTPUT.PUT_LINE('=====================================');
    DBMS_OUTPUT.PUT_LINE(SUBSTR(v_online_ddl, 1, 2000)); -- Show first 2000 chars
    DBMS_OUTPUT.PUT_LINE('... (complete script generated by package)');
    DBMS_OUTPUT.PUT_LINE('=====================================');
    
END;
/

-- =====================================================
-- EXAMPLE: Different Configuration Options
-- =====================================================

PROMPT
PROMPT Example: Different Redefinition Configurations
PROMPT

DECLARE
    v_ddl CLOB;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== EXAMPLE: 4 SUBPARTITIONS WITH 3 TABLESPACES ===');
    
    -- Example with more subpartitions and tablespaces
    v_ddl := table_ops_pkg.generate_online_subpartitioning_ddl(
        p_table_name            => 'CIM_OFM_SMG3_LOGGING_SIMPLE',
        p_subpartition_column   => 'TRACE_ID',
        p_subpartition_type     => 'HASH',
        p_tablespace_list       => 'MAV_LOB,MAV_HIST_LOB,DBRT_DATA',
        p_subpartition_count    => 4, -- Round-robin: TS1,TS2,TS3,TS1
        p_parallel_degree       => 8
    );
    
    DBMS_OUTPUT.PUT_LINE('Configuration: 4 subpartitions across 3 tablespaces');
    DBMS_OUTPUT.PUT_LINE('Round-robin distribution with higher parallelism');
    DBMS_OUTPUT.PUT_LINE('Script generated - ready for execution');
    
END;
/

-- =====================================================
-- COMPARISON: DBMS_REDEFINITION vs Manual Recreation
-- =====================================================

PROMPT
PROMPT ========================================
PROMPT COMPARISON: DBMS_REDEFINITION vs MANUAL
PROMPT ========================================
PROMPT
PROMPT 🚀 DBMS_REDEFINITION ADVANTAGES:
PROMPT   ✅ ONLINE operation - minimal downtime (seconds)
PROMPT   ✅ Automatic data synchronization during redefinition
PROMPT   ✅ Preserves all dependent objects (indexes, triggers, etc.)
PROMPT   ✅ Atomic switch at the end
PROMPT   ✅ Can abort and rollback if issues occur
PROMPT   ✅ Built-in Oracle feature - fully supported
PROMPT   ✅ Handles large tables efficiently
PROMPT
PROMPT 📋 MANUAL RECREATION ADVANTAGES:
PROMPT   ✅ Full control over the process
PROMPT   ✅ Simpler to understand and troubleshoot
PROMPT   ✅ Can modify structure more extensively
PROMPT   ✅ Better for smaller tables
PROMPT
PROMPT 🎯 WHEN TO USE DBMS_REDEFINITION:
PROMPT   → Production tables with high availability requirements
PROMPT   → Large tables (>1GB)
PROMPT   → Tables with many dependent objects
PROMPT   → 24/7 systems with minimal maintenance windows
PROMPT
PROMPT 🎯 WHEN TO USE MANUAL RECREATION:
PROMPT   → Development/test environments
PROMPT   → Smaller tables (<1GB)
PROMPT   → Major structural changes required
PROMPT   → Learning/understanding the process
PROMPT
PROMPT ⚡ PERFORMANCE COMPARISON:
PROMPT   DBMS_REDEFINITION: ~5-15 seconds downtime
PROMPT   Manual Recreation: Full table unavailable during copy
PROMPT
PROMPT ========================================
PROMPT YOUR RECOMMENDATION: Use DBMS_REDEFINITION
PROMPT ========================================
PROMPT Reason: You have an existing production-like table
PROMPT         that needs subpartitioning with minimal impact
PROMPT ========================================
PROMPT
PROMPT 🎯 IMPLEMENTATION NOTE:
PROMPT   All actual DBMS_REDEFINITION code is in table_ops_pkg
PROMPT   This file contains USAGE examples only
PROMPT ========================================